<a href="https://colab.research.google.com/github/haseeb1zahid/Data-Analysis-And-Visualization/blob/master/IBA_Hackathon.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from keras.utils import np_utils
from sklearn import preprocessing
from imblearn.over_sampling import SMOTE

Using TensorFlow backend.


In [2]:
data = pd.read_csv('training.csv')
data.head()

Row_ID  Financial_Year Branch_Code  Sequence_1  Sequence_2 Donation_type  \
0  202961              15       BRC-2     16281.0       15682             R   
1   43390              15       BRC-1      1528.0         294             T   
2  102493              16       BRC-1     27502.0       25159             T   
3  122646              17       BRC-1      8252.0        7796             R   
4   58944              15       BRC-1     17715.0       16483             R   

   Donor_Age Donation_Date Gender  Blood_Group_Code  Donor_Weight  \
0       23.0     20-May-15      M               5.0           NaN   
1       20.0      4-Jul-14      M               5.0          82.0   
2       38.0     22-Feb-16      M               7.0          80.0   
3       25.0     29-Aug-16      M               1.0          60.0   
4       22.0     28-Nov-14      M               7.0          75.0   

   Donor_Temperature  Donor_Pulse  Donor_Hemoglobin Donor_Blood_Pressure  \
0                NaN          NaN               NaN                  NaN   
1               37.0         72.0              14.0               120/80   
2               37.0         72.0              13.0               120/80   
3               37.0         78.0              13.0               120/80   
4               37.0         72.0              14.0               120/80   

   Test_1  Test_2 Test_3 Test_4  Y  
0   0.132   0.192      N      N  0  
1   0.649   0.724      N      N  0  
2   0.082   0.202      N      N  0  
3   0.144   0.183      N      N  0  
4   0.424   0.303      N      N  0

In [3]:
data['Y'].unique()
data['Y'].count()

164599

In [0]:
data = data.dropna()

In [0]:
y_train = data['Y']

In [6]:
y_train.unique()

array([0, 1])

In [7]:
y_train.count()

139571

In [8]:
data.count()

Row_ID                  139571
Financial_Year          139571
Branch_Code             139571
Sequence_1              139571
Sequence_2              139571
Donation_type           139571
Donor_Age               139571
Donation_Date           139571
Gender                  139571
Blood_Group_Code        139571
Donor_Weight            139571
Donor_Temperature       139571
Donor_Pulse             139571
Donor_Hemoglobin        139571
Donor_Blood_Pressure    139571
Test_1                  139571
Test_2                  139571
Test_3                  139571
Test_4                  139571
Y                       139571
dtype: int64

In [9]:
data['Test_4'].unique()

array(['N'], dtype=object)

In [0]:
del data['Row_ID']
del data['Financial_Year']
del data['Branch_Code']
del data['Donation_Date']
del data['Test_4']

In [11]:
# encode class values as integers
encoder = LabelEncoder()
encoder.fit(data['Donation_type'])
Donation_type = encoder.transform(data['Donation_type'])
Donation_type = np_utils.to_categorical(Donation_type)
print(Donation_type[0])

[0. 0. 0. 0. 0. 0. 1.]


In [0]:
data['Donation_type'] = Donation_type

In [0]:
encoder = LabelEncoder()
encoder.fit(data['Gender'])
Gender = encoder.transform(data['Gender'])
data['Gender'] = Gender

In [0]:
encoder = LabelEncoder()
encoder.fit(data['Donor_Blood_Pressure'])
Donor_Blood_Pressure = encoder.transform(data['Donor_Blood_Pressure'])
data['Donor_Blood_Pressure'] = Donor_Blood_Pressure

In [0]:
encoder = LabelEncoder()
encoder.fit(data['Test_3'])
Test_3 = encoder.transform(data['Test_3'])
data['Test_3'] = Test_3

In [17]:
data.head()

Sequence_1  Sequence_2  Donation_type  Donor_Age  Gender  Blood_Group_Code  \
1      1528.0         294            0.0       20.0       1               5.0   
2     27502.0       25159            0.0       38.0       1               7.0   
3      8252.0        7796            0.0       25.0       1               1.0   
4     17715.0       16483            0.0       22.0       1               7.0   
5     17875.0       17419            0.0       44.0       1               1.0   

   Donor_Weight  Donor_Temperature  Donor_Pulse  Donor_Hemoglobin  \
1          82.0               37.0         72.0              14.0   
2          80.0               37.0         72.0              13.0   
3          60.0               37.0         78.0              13.0   
4          75.0               37.0         72.0              14.0   
5          80.0               37.0         78.0              13.0   

   Donor_Blood_Pressure  Test_1  Test_2  Test_3  Y  
1                   183   0.649   0.724       0  0  
2                   183   0.082   0.202       0  0  
3                   183   0.144   0.183       0  0  
4                   183   0.424   0.303       0  0  
5                   183   0.144   0.152       0  0

In [18]:
data = data.values
x = data[:,0:14]
x[0]

array([1.528e+03, 2.940e+02, 0.000e+00, 2.000e+01, 1.000e+00, 5.000e+00,
       8.200e+01, 3.700e+01, 7.200e+01, 1.400e+01, 1.830e+02, 6.490e-01,
       7.240e-01, 0.000e+00])

In [19]:
min_max_scaler = preprocessing.MinMaxScaler()
x_train = min_max_scaler.fit_transform(x)
print(x_train[0])

[9.70849863e-03 6.61160755e-03 0.00000000e+00 2.63748567e-02
 1.00000000e+00 2.94117647e-01 1.52830189e-01 3.67477721e-02
 8.18106694e-02 1.94838945e-02 3.77319588e-01 7.26054737e-04
 1.02100877e-04 0.00000000e+00]


In [0]:
df = pd.DataFrame(x_train)
df.to_csv('clean_x_train.csv')

In [21]:
np.unique(y_train)

array([0, 1])

In [0]:
df = pd.DataFrame(y_train)
df.to_csv('clean_y_train.csv')

In [0]:
smt = SMOTE()
X_train, y_train = smt.fit_sample(x_train, y_train)

In [31]:
X_train.shape

(273732, 14)

In [32]:
y_train.shape

(273732,)

In [33]:
X_train

array([[9.70849863e-03, 6.61160755e-03, 0.00000000e+00, ...,
        7.26054737e-04, 1.02100877e-04, 0.00000000e+00],
       [2.23049060e-01, 5.67695640e-01, 0.00000000e+00, ...,
        9.17357295e-05, 2.83848912e-05, 0.00000000e+00],
       [6.49368783e-02, 1.75895839e-01, 0.00000000e+00, ...,
        1.61096891e-04, 2.57017423e-05, 0.00000000e+00],
       ...,
       [2.53760099e-01, 6.76531642e-01, 0.00000000e+00, ...,
        1.70673666e-04, 2.09182565e-05, 0.00000000e+00],
       [9.47318034e-01, 8.55267246e-01, 0.00000000e+00, ...,
        2.89358168e-04, 3.30665826e-05, 0.00000000e+00],
       [1.08686865e-01, 2.86190084e-01, 0.00000000e+00, ...,
        2.72863143e-04, 3.86776472e-05, 0.00000000e+00]])

In [0]:
y_train = y_train.astype(float)

In [36]:
y_train

array([0., 0., 0., ..., 1., 1., 1.])

In [50]:
from __future__ import absolute_import, division, print_function, unicode_literals

!pip install -q tensorflow==2.0.0-alpha0

    100% |████████████████████████████████| 79.9MB 586kB/s 
    100% |████████████████████████████████| 419kB 19.0MB/s 
    100% |████████████████████████████████| 3.0MB 15.1MB/s 
    100% |████████████████████████████████| 61kB 30.7MB/s 


In [56]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(128 ,activation='relu', input_shape=(14,)),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.


In [0]:
model.compile(optimizer='rmsprop',
                loss='binary_crossentropy',
                metrics=['accuracy'])

In [62]:
model.fit(X_train, y_train, shuffle=True, epochs=100, batch_size=200)

Epoch 1/100
273732/273732 [==============================] - 4s 15us/sample - loss: 0.6682 - acc: 0.5812
Epoch 2/100
273732/273732 [==============================] - 4s 15us/sample - loss: 0.6676 - acc: 0.5826
Epoch 3/100
273732/273732 [==============================] - 4s 14us/sample - loss: 0.6669 - acc: 0.5840
Epoch 4/100
273732/273732 [==============================] - 4s 15us/sample - loss: 0.6664 - acc: 0.5849
Epoch 5/100
273732/273732 [==============================] - 4s 15us/sample - loss: 0.6660 - acc: 0.5850
Epoch 6/100
273732/273732 [==============================] - 4s 14us/sample - loss: 0.6653 - acc: 0.5856
Epoch 7/100
273732/273732 [==============================] - 4s 14us/sample - loss: 0.6648 - acc: 0.5875
Epoch 8/100
273732/273732 [==============================] - 4s 14us/sample - loss: 0.6647 - acc: 0.5880
Epoch 9/100
273732/273732 [==============================] - 4s 14us/sample - loss: 0.6638 - acc: 0.5891
Epoch 10/100
273732/273732 [===========================

In [63]:
data = pd.read_csv('test_data.csv')
data.head()

Row_ID  Financial_Year Branch_Code  Sequence_1  Sequence_2 Donation_type  \
0  143624              17       BRC-1     29996.0       29540             R   
1  148736              17       BRC-1     35296.0       34840             M   
2    8388              14       BRC-1     86369.0        8590             R   
3   48199              15       BRC-1      6521.0        5289             M   
4   90631              16       BRC-1     15197.0       12853             P   

   Donor_Age Donation_Date Gender  Blood_Group_Code  Donor_Weight  \
0       25.0     16-Mar-17      M               NaN          65.0   
1       23.0      7-May-17      M               7.0          60.0   
2       26.0      4-Sep-13      M               1.0          65.0   
3       30.0     16-Aug-14      M               3.0          85.0   
4        NaN     25-Oct-15      M               5.0           NaN   

   Donor_Temperature  Donor_Pulse  Donor_Hemoglobin Donor_Blood_Pressure  \
0               37.0         72.0              13.0               120/80   
1               37.0         72.0              12.0               120/80   
2               37.0         72.0              13.0               120/80   
3               37.0         72.0              14.0               120/80   
4                NaN          NaN               NaN                  NaN   

   Test_1  Test_2 Test_3 Test_4  
0   0.122   0.194      N      N  
1   0.213   0.221      N      N  
2   0.151   0.394      N      N  
3   0.203   0.272      N      N  
4   0.382   0.182      N      N

In [0]:
del data['Row_ID']
del data['Financial_Year']
del data['Branch_Code']
del data['Donation_Date']
del data['Test_4']

data.fillna(df.mean(), inplace=True)

In [0]:
data.dropna(inplace=True)

In [73]:
data.head()

Sequence_1  Sequence_2  Donation_type  Donor_Age Gender  Blood_Group_Code  \
0     29996.0       29540            0.0       25.0      M          3.608659   
1     35296.0       34840            0.0       23.0      M          7.000000   
2     86369.0        8590            0.0       26.0      M          1.000000   
3      6521.0        5289            0.0       30.0      M          3.000000   
6      9290.0        8502            0.0       32.0      M          3.000000   

   Donor_Weight  Donor_Temperature  Donor_Pulse  Donor_Hemoglobin  \
0          65.0               37.0         72.0              13.0   
1          60.0               37.0         72.0              12.0   
2          65.0               37.0         72.0              13.0   
3          85.0               37.0         72.0              14.0   
6          70.0               37.0         72.0              12.0   

  Donor_Blood_Pressure  Test_1  Test_2 Test_3  
0               120/80   0.122   0.194      N  
1               120/80   0.213   0.221      N  
2               120/80   0.151   0.394      N  
3               120/80   0.203   0.272      N  
6               120/70   0.051   0.134      N

In [0]:
# encode class values as integers
encoder = LabelEncoder()

encoder.fit(data['Donation_type'])
Donation_type = encoder.transform(data['Donation_type'])
Donation_type = np_utils.to_categorical(Donation_type)
data['Donation_type'] = Donation_type

In [0]:
encoder = LabelEncoder()
encoder.fit(data['Gender'])
Gender = encoder.transform(data['Gender'])
data['Gender'] = Gender

In [0]:
encoder = LabelEncoder()
encoder.fit(data['Donor_Blood_Pressure'])
Donor_Blood_Pressure = encoder.transform(data['Donor_Blood_Pressure'])
data['Donor_Blood_Pressure'] = Donor_Blood_Pressure

In [0]:
encoder = LabelEncoder()
encoder.fit(data['Test_3'])
Test_3 = encoder.transform(data['Test_3'])
data['Test_3'] = Test_3

In [79]:
data.head()

min_max_scaler = preprocessing.MinMaxScaler()
x_test = min_max_scaler.fit_transform(x)
print(x_test[0])

df = pd.DataFrame(x_test)
df.to_csv('clean_x_test.csv')

[9.70849863e-03 6.61160755e-03 0.00000000e+00 2.63748567e-02
 1.00000000e+00 2.94117647e-01 1.52830189e-01 3.67477721e-02
 8.18106694e-02 1.94838945e-02 3.77319588e-01 7.26054737e-04
 1.02100877e-04 0.00000000e+00]


In [0]:
predictions = model.predict(x_test)
predictions = np.where(predictions > 0.5, 1, 0)

In [91]:
predictions

0
0       0
1       1
2       1
3       0
4       0
5       1
6       0
7       0
8       1
9       1
10      1
11      0
12      0
13      0
14      1
15      1
16      1
17      0
18      0
19      0
20      0
21      1
22      1
23      0
24      0
25      1
26      0
27      0
28      1
29      1
...    ..
139541  0
139542  0
139543  1
139544  0
139545  1
139546  1
139547  1
139548  0
139549  0
139550  1
139551  1
139552  0
139553  1
139554  1
139555  0
139556  1
139557  1
139558  1
139559  0
139560  1
139561  0
139562  1
139563  1
139564  0
139565  0
139566  1
139567  1
139568  0
139569  1
139570  1

[139571 rows x 1 columns]

In [0]:
predictions = pd.DataFrame(predictions)

In [90]:
predictions.count()

0    139571
dtype: int64